CREATE TABLE "clicks_on_short_urls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clicks_on_short_urls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"click_count" timestamp DEFAULT now() NOT NULL,
	"short_url_id" varchar,
	"user_agent" varchar(255) NOT NULL,
	"ip_address" varchar(255) NOT NULL,
	"referer" varchar(255) NOT NULL,
	"created_at" varchar(255) DEFAULT '2025-09-03T07:46:12.233Z' NOT NULL,
	"updated_at" varchar(255) DEFAULT '2025-09-03T07:46:12.233Z' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "short_urls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "short_urls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"short_urlID" varchar(155) NOT NULL,
	"long_url" varchar(555) NOT NULL,
	"user_id" integer,
	"created_at" varchar(255) DEFAULT '2025-09-03T07:46:12.232Z' NOT NULL,
	"updated_at" varchar(255) DEFAULT '2025-09-03T07:46:12.232Z' NOT NULL,
	CONSTRAINT "short_urls_short_urlID_unique" UNIQUE("short_urlID")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"refresh_token" varchar(255),
	"created_at" varchar(255) DEFAULT '2025-09-03T07:46:12.230Z' NOT NULL,
	"updated_at" varchar(255) DEFAULT '2025-09-03T07:46:12.231Z' NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "clicks_on_short_urls" ADD CONSTRAINT "clicks_on_short_urls_short_url_id_short_urls_short_urlID_fk" FOREIGN KEY ("short_url_id") REFERENCES "public"."short_urls"("short_urlID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "short_urls" ADD CONSTRAINT "short_urls_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_short_urls_user_id" ON "short_urls" USING btree ("user_id");